### ISSUE TITLE
$user in custom reason

### ISSUE THREAD

**Issue by MelanX** [derNiklaas/Voteban-Plugin#2]
![image](https://user-images.githubusercontent.com/26039509/60825883-fb0eaa80-a1ac-11e9-9199-8478db2b0600.png)
If you type in a custom reason with $user it will not be replaced.

**Comment by derNiklaas** [comment]
Just a question: Why would you do like to have that Feature?

**Comment by MelanX** [comment]
If someone has a very complicate name it is easier to use this.

**Comment by derNiklaas** [comment]
I will check your code (Even tho it‘s just a copy of the Code for the normal) when I‘ll arive at Home. (in aprox. 12h)

**Comment by MelanX** [comment]
But it works very well D: trust me, pls D:
